name: Update Hugo Blog in React App

# Trigger this workflow on a repository dispatch event
on:
  repository_dispatch:
    types: [hugo_update]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the dev branch of the React repository
      - name: Checkout React Repository
        uses: actions/checkout@v3
        with:
          ref: dev # Specify the dev branch

      # Step 2: Clone the Hugo repository into a subfolder using the ET_GT_TOKEN secret
      - name: Clone Hugo Repository
        env:
          GH_TOKEN: ${{ secrets.ET_GT_TOKEN }} # Set the token as an environment variable
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/Ayansh-Modules/embrays-blogs.git hugo

      # Step 3: Copy the Hugo output to the React app's public/blogs folder
      - name: Copy Hugo Output to React Public Folder
        run: |
          rm -rf public/blogs/*         # Clear the existing blogs folder
          mkdir -p public/blogs          # Create the blogs folder if it doesn't exist
          cp -r hugo/public/* public/blogs/   # Copy the built Hugo site to React public/blogs
          rm -rf hugo

      # Step 4: Commit and push the changes to the dev branch
      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update blogs from Hugo"
          git push origin dev  # Push to dev branch
